version: '3.9'

services:
  warehouseapp:
    build:
      context: .
    command: bash /warehouse/start-dev.sh
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_RABBITMQ_HOST: rabbitmq-storefront  # conecta ao RabbitMQ do Storefront
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - .:/warehouse
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true
